"""Where the built database lives on disk, and how to read and write it.

It used to be a single 10,800-line exercises_db.json. Adding one exercise meant a
diff somewhere in the middle of it, and two people adding one at the same time
conflicted every time -- which is a poor way to run a pack that wants
contributions.

It is now an index plus one small file per exercise:

    engine/config/index.json          totals, and which exercise sits where
    engine/config/exercises/aff_a.json

so adding an exercise is a new file plus a few lines in the index. Everything
here is generated by engine/scripts/build_db.py; nothing in engine/config/ is
written by hand.
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_DIR = os.path.join(BASE_DIR, "engine", "config")
INDEX_NAME = "index.json"
EXERCISES_NAME = "exercises"

WARNING = "Generated file. Edit exercises/, then run engine/scripts/build_db.py."


def index_path(config_dir=None):
    return os.path.join(config_dir or CONFIG_DIR, INDEX_NAME)


def exercises_dir(config_dir=None):
    return os.path.join(config_dir or CONFIG_DIR, EXERCISES_NAME)


def empty():
    return {"total_exercises": 0, "total_tests": 0, "tracks": {}, "exercises": {}}


def load(config_dir=None):
    """The whole database as one dict, or an empty one if it is not built yet."""
    path = index_path(config_dir)
    if not os.path.isfile(path):
        return empty()
    with open(path, encoding="utf-8") as f:
        database = json.load(f)

    database["exercises"] = {}
    directory = exercises_dir(config_dir)
    if os.path.isdir(directory):
        for filename in sorted(os.listdir(directory)):
            if not filename.endswith(".json"):
                continue
            with open(os.path.join(directory, filename), encoding="utf-8") as f:
                entry = json.load(f)
            database["exercises"][entry["name"]] = entry
    return database


def write(database, config_dir=None):
    """Write the index and one file per exercise, pruning anything left over.

    Pruning matters: renaming an exercise would otherwise leave the old file
    behind, and it would go on being loaded and graded for ever.
    """
    directory = exercises_dir(config_dir)
    os.makedirs(directory, exist_ok=True)

    entries = database["exercises"]
    for name, entry in entries.items():
        _write_json(os.path.join(directory, f"{name}.json"), entry)

    written = {f"{name}.json" for name in entries}
    removed = []
    for filename in sorted(os.listdir(directory)):
        if filename.endswith(".json") and filename not in written:
            os.remove(os.path.join(directory, filename))
            removed.append(filename)

    index = {key: value for key, value in database.items() if key != "exercises"}
    _write_json(index_path(config_dir), index)
    return removed


def _write_json(path, payload):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, ensure_ascii=False)
        f.write("\n")
